[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "conehead"
version = "0.1.0"
description = "A collapsed-cone convolution radiotherapy dose calculation algorithm written in Python/CUDA."
readme = "README.md"
requires-python = ">=3.9"
authors = [{ name = "Samuel Peet", email = "samuelpeet@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Private :: Do Not Upload",
]

dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "scipy>=1.16.2",
    "pydicom>=3.0.1",
    "toml>=0.10.2",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["I"]
