# Siemens Confidence RT Pro calibration for CT number to mass density conversion

[LUT]
hu = [
    -978,  # Air
    -709,  # LN-300 Lung
    -518,  # LN-450 Lung
    -94,   # AP6 Adipose
    -52,   # BR-12 Breast
    -4,    # Water
    21,    # BRN-SR2 Brain
    64,    # LV1 Liver 
    196,   # IB Inner Bone
    209,   # B200 Bone Mineral
    431,   # CB2-30% CaCO3
    786,   # CB2-50% CaCO3
    1181,  # SB3 Cortical Bone
    7308,  # Titanium
    31743, # Arbitrary upper bound (extrap. from SB3 and Ti)
]
density = [
    0.00121, # Air
    0.3,     # LN-300 Lung
    0.5,     # LN-450 Lung
    0.943,   # AP6 Adipose
    0.979,   # BR-12 Breast
    1.0,     # Water
    1.053,   # BRN-SR2 Brain
    1.09,    # LV1 Liver 
    1.14,    # IB Inner Bone
    1.152,   # B200 Bone Mineral
    1.335,   # CB2-30% CaCO3
    1.559,   # CB2-50% CaCO3
    1.823,   # SB3 Cortical Bone
    4.59,    # Titanium
    15.63,   # Arbitrary upper bound (extrap. from SB3 and Ti)
]
