# Siemens Confidence RT Pro calibration for CT number to mass density conversion

[LUT]
hu = [
    -972,  # Air
    -710,  # LN-300 Lung
    -514,  # LN-450 Lung
    -91,   # AP6 Adipose
    -47,   # BR-12 Breast
    -2,    # Water
    24,    # BRN-SR2 Brain
    66,    # LV1 Liver 
    194,   # IB Inner Bone
    211,   # B200 Bone Mineral
    423,   # CB2-30% CaCO3
    772,   # CB2-50% CaCO3
    1164,  # SB3 Cortical Bone
    5808,  # Titanium
    30657, # Arbitrary upper bound (extrap. from SB3 and Ti)
]
density = [
    0.00121, # Air
    0.3,     # LN-300 Lung
    0.5,     # LN-450 Lung
    0.943,   # AP6 Adipose
    0.979,   # BR-12 Breast
    1.0,     # Water
    1.053,   # BRN-SR2 Brain
    1.09,    # LV1 Liver 
    1.14,    # IB Inner Bone
    1.152,   # B200 Bone Mineral
    1.335,   # CB2-30% CaCO3
    1.559,   # CB2-50% CaCO3
    1.823,   # SB3 Cortical Bone
    4.59,    # Titanium
    15.63,   # Arbitrary upper bound (extrap. from SB3 and Ti)
]
